### ISSUE TITLE
Gm-ID testbenches 

### ISSUE THREAD

**Issue by leochand101** [AugustUnderground/pyspectre#3]
@AugustUnderground have you done gm-id sims for any tech you are working on?
I am planning to write some for  technologies I am working on, if you have some already I will reuse them otherwise I had done one for pySpice (https://github.com/PySpice-org/PySpice/pull/332/files) I will try and replicate it here in pySpectre.

**Comment by AugustUnderground** [comment]
I have generated a lot of gm/Id lookup-tables, mainly for training data. I've not used `pyspectre` for this though, as I just need the data and no interactivity. Here is a simple netlist used for just that, the results are read with [pynut](https://github.com/AugustUnderground/pynut) and stored as `pandas.DataFrame` or `torch.tensor`. Are you looking to create these tables, or do you need to interactively draw the curves on demand with an open spectre session? In case of the latter, I have nothing for you to re-use, sorry.

```
simulator lang=spectre
global 0

parameters L=180n Lmin=180n Lmax=20u vb=0.0 vg=0.0 vd=0.0 vs=0.0 W=10.0u vdd=1.8 M=1

include "/path/to/gpdk180_v3.3/models/spectre/nmos1.scs" section=nom

save W L M temp                     \
     M0:vds M0:vgs M0:vbs           \
     M0:vdsat M0:vearly M0:vth      \
     M0:gm M0:gds M0:gmbs           \
     M0:ron M0:rout                 \
     M0:id M0:fug M0:pwr            \
     M0:betaeff M0:region           \
     M0:self_gain M0:gmoverid       \
     M0:cbb M0:csb M0:cdb M0:cgb    \
     M0:css M0:csd M0:csg M0:cds    \
     M0:cdd M0:cdg M0:cbs M0:cbd    \
     M0:cbg M0:cgd M0:cgs M0:cgg    \

M0 (D G S B) nmos1 m=M w=W l=L // ... derived instance parameters ...

VD (D S) vsource dc=vd type=dc
VG (G S) vsource dc=vg type=dc
VS (S 0) vsource dc=vs type=dc
VB (B S) vsource dc=vb type=dc

simulatorOptions options save=selected rawfmt=nutbin

length sweep param=L start=Lmin stop=Lmax log=10 {
  bulk sweep param=vb start=vs stop=-1.5 step=-0.25 {
    drain sweep param=vd start=vs stop=vdd step=0.025 {
      dc dc param=vg start=vs stop=vdd step=0.025 
    }
  }
}
```

**Comment by leochand101** [comment]
No this is pretty much what I am looking at I guess all the simulations params are already swept here. Once in a dataframe I can easily plot whatever I want, eventually I woud like to get into pytorch for param space search( which is what you are doing I believe).
