### ISSUE TITLE
No module named 'distutils.msvccompiler'

### ISSUE THREAD

**Issue by papageeleni** [AugustUnderground/pyspectre#6]
Hello, Im trying to install pyspectre using the suggested: `pip install git+https://github.com/augustunderground/pyspectre.git`.
Im getting the error :
```
× Preparing metadata (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [26 lines of output]
.
.
.
ModuleNotFoundError: No module named 'distutils.msvccompiler'
[end of output]
      
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

python: 3.11.5

**Comment by papageeleni** [comment]
Seems like `sudo apt install unixodbc-dev` solves the issues

**Comment by AugustUnderground** [comment]
That's interesting. I've not encountered this before. I see you're installing a missing package with `apt`, are you on Debian or Ubuntu? AFAIK Cadence does not support spectre on these platforms. Eitherway I'm glad you could resolve the issue so i'll close this.
